# Generated by Django 4.0.8 on 2022-12-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetups", "0004_alter_meetup_location_alter_rsvp_meetup_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="map_image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
