[pycodestyle]
max-line-length = 120

[tool.black]
target-version = ['py38']
line-length = 120
include = '\.pyi?$'
exclude = '''
/(
  \.git
  | build
  | dist
 )/
'''

[tool.isort]
profile = "black"
line_length = 120
default_section = "THIRDPARTY"
known_first_party = "pygraz_website"
skip_glob = "venv"

[tool.pytest.ini_options]
addopts = """\
    --strict-config
    --strict-markers
    """
filterwarnings = [
    "default",
    "ignore:.*'django_extensions' defines default_app_config",
]
minversion = "7.2"
testpaths = [
    "tests",
]
DJANGO_SETTINGS_MODULE = "pygraz_website.settings.testing"
