---
- hosts: localhost
  any_errors_fatal: true
  vars:
    - root: ../..
  tasks:
    - stat:
        path: "{{ root }}/.venv"
      register: venv
    - name: Create virtualenv if missing
      when: not venv.stat.exists
      shell: "virtualenv {{ root }}/.venv"
    - name: Install all dependencies
      shell: "{{ root }}/.venv/bin/pip install -r {{ root }}/requirements/base.txt"
    - name: Build CSS
      shell: compass compile -s compact
      args:
        chdir: "{{ root }}/pygraz_website/static"
    - name: Compile messages
      shell: "../.venv/bin/django-admin.py compilemessages"
      args:
        chdir: "{{ root}}/pygraz_website"
    - name: Clean up previous artifacts
      file:
        path: production.zip
        state: absent
    - name: Build production.zip
      shell: "zip -x@production-exclude.lst -r production.zip *"
      args:
        chdir: "{{ root }}"
- hosts: live
  become_user: www-pygraz
  become: true
  tasks:
    - name: Unzip package
      unarchive:
        src: ../../production.zip
        dest: /srv/www/pygraz.org/live/app/
    - name: Install dependencies
      shell: "CC=`which clang` ./env/bin/pip install -r app/requirements/live.txt"
      args:
        chdir: /srv/www/pygraz.org/live
- hosts: live
  tasks:
    - name: Restart server
      shell: systemctl restart www-pygraz
